[package]
name = "kafka-net"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
kafka-protocol = { path = "../kafka-protocol" }
kafka-errors = { path = "../kafka-errors" }
thiserror = "2"

[dev-dependencies]
kafka-record = { path = "../kafka-record" }
kafka-compress = { path = "../kafka-compress" }

[lints.rust]
unsafe_code = "deny"
