[workspace]
resolver = "2"
members = [
    "crates/kafka-protocol",
    "crates/kafka-record",
    "crates/kafka-common",
    "crates/kafka-errors",
    "crates/kafka-storage",
    "crates/kafka-net",
    "crates/kafka-compress",
    "crates/kafka-metadata",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/apache/kafka"
