[package]
name = "kafka-server"
version = "0.1.0"
edition = "2021"

[dependencies]
kafka-common = { path = "../kafka-common" }
kafka-server-common = { path = "../kafka-server-common" }
kafka-net = { path = "../kafka-net" }
kafka-protocol = { path = "../kafka-protocol" }
kafka-record = { path = "../kafka-record" }
kafka-storage = { path = "../kafka-storage" }
tokio = { version = "1.0", features = ["full"] }
thiserror = "2"

[dev-dependencies]
rdkafka = { version = "0.37", features = ["tokio"] }

[lints.rust]
unsafe_code = "deny"
